import json

QUESTIONS = [
    {"id": "c1-md-1", "exam": "core1", "domain": "Mobile Devices",
     "q": "Which connector type is standard for charging and data transfer on current-generation Android smartphones?",
     "options": ["USB-C", "Micro-USB", "Lightning", "USB-A"], "correct": 0,
     "exp": "USB-C is the standard connector on modern Android devices, replacing Micro-USB, and offers faster charging and data transfer."},
    {"id": "c1-md-2", "exam": "core1", "domain": "Mobile Devices",
     "q": "A technician wants the fastest storage upgrade for a laptop that connects directly to the motherboard with no cabling. What should they install?",
     "options": ["3.5\" HDD", "2.5\" SATA SSD", "NVMe M.2 SSD", "eMMC card"], "correct": 2,
     "exp": "NVMe M.2 SSDs connect directly to the motherboard via the PCIe bus, giving far higher throughput than SATA-based drives."},
    {"id": "c1-md-3", "exam": "core1", "domain": "Mobile Devices",
     "q": "Which wireless technology enables contactless payments like Apple Pay or Google Pay?",
     "options": ["Bluetooth", "NFC", "Infrared", "Wi-Fi Direct"], "correct": 1,
     "exp": "NFC (Near Field Communication) works at very short range and is the technology behind tap-to-pay features."},
    {"id": "c1-md-4", "exam": "core1", "domain": "Mobile Devices",
     "q": "What is the main purpose of Mobile Device Management (MDM) software in a business environment?",
     "options": ["Compress photos automatically", "Centrally enforce security policy and manage devices remotely", "Increase battery life", "Unlock carrier restrictions"], "correct": 1,
     "exp": "MDM lets IT push policies, wipe lost devices, enforce encryption, and manage apps across a fleet of company devices from one console."},
    {"id": "c1-md-5", "exam": "core1", "domain": "Mobile Devices",
     "q": "A laptop's battery has visibly swollen and the case is bulging. What should the technician do first?",
     "options": ["Keep charging it to drain it faster", "Power it off, stop using it, and handle it carefully for safe disposal", "Puncture the battery to release pressure", "Ignore it if the laptop still boots"], "correct": 1,
     "exp": "A swollen lithium battery is a fire/chemical hazard. Power down immediately, avoid pressure or punctures, and dispose of it per hazmat procedures."},

    {"id": "c1-nw-1", "exam": "core1", "domain": "Networking",
     "q": "Which protocol translates domain names like example.com into IP addresses?",
     "options": ["DHCP", "DNS", "FTP", "SNMP"], "correct": 1,
     "exp": "DNS (Domain Name System) is the internet's directory service, resolving human-readable names to IP addresses."},
    {"id": "c1-nw-2", "exam": "core1", "domain": "Networking",
     "q": "What is the default port for HTTPS traffic?",
     "options": ["80", "21", "443", "3389"], "correct": 2,
     "exp": "Port 443 is the standard port for HTTPS (encrypted HTTP over TLS). Port 80 is plain HTTP."},
    {"id": "c1-nw-3", "exam": "core1", "domain": "Networking",
     "q": "Wi-Fi 6 is based on which IEEE wireless standard?",
     "options": ["802.11n", "802.11ac", "802.11ax", "802.11g"], "correct": 2,
     "exp": "802.11ax is the technical designation for Wi-Fi 6, offering better throughput and efficiency in crowded environments than 802.11ac (Wi-Fi 5)."},
    {"id": "c1-nw-4", "exam": "core1", "domain": "Networking",
     "q": "Which device operates at Layer 3 and forwards traffic between different networks?",
     "options": ["Switch", "Hub", "Router", "Repeater"], "correct": 2,
     "exp": "Routers work at the Network layer, using IP addresses to move traffic between separate networks or subnets."},
    {"id": "c1-nw-5", "exam": "core1", "domain": "Networking",
     "q": "What does DHCP do on a network?",
     "options": ["Encrypts wireless traffic", "Automatically assigns IP addresses to devices", "Filters malicious traffic", "Translates private to public IPs"], "correct": 1,
     "exp": "DHCP (Dynamic Host Configuration Protocol) automatically leases IP addresses and other network settings to devices as they join the network."},

    {"id": "c1-hw-1", "exam": "core1", "domain": "Hardware",
     "q": "Which RAM type is standard in newly built desktop PCs as of the current generation?",
     "options": ["DDR3", "DDR4", "DDR5", "SDRAM"], "correct": 2,
     "exp": "DDR5 is the current-generation memory standard, offering higher bandwidth and capacity than DDR4."},
    {"id": "c1-hw-2", "exam": "core1", "domain": "Hardware",
     "q": "Which connector provides the main power feed from the PSU to the motherboard?",
     "options": ["4-pin Molex", "24-pin ATX", "SATA power", "6-pin PCIe"], "correct": 1,
     "exp": "The 24-pin ATX connector is the primary power connection between the power supply and motherboard."},
    {"id": "c1-hw-3", "exam": "core1", "domain": "Hardware",
     "q": "What is the role of the power supply unit (PSU) in a desktop computer?",
     "options": ["Cools the CPU", "Converts AC wall power to DC power for components", "Stores boot instructions", "Manages RAM timing"], "correct": 1,
     "exp": "The PSU converts alternating current from the wall outlet into the direct current voltages (12V, 5V, 3.3V) components need."},
    {"id": "c1-hw-4", "exam": "core1", "domain": "Hardware",
     "q": "Which motherboard form factor is physically smaller than ATX but larger than Mini-ITX?",
     "options": ["E-ATX", "MicroATX", "Nano-ITX", "BTX"], "correct": 1,
     "exp": "MicroATX sits between full ATX and Mini-ITX in size, offering fewer expansion slots than ATX while still supporting standard components."},
    {"id": "c1-hw-5", "exam": "core1", "domain": "Hardware",
     "q": "Which display connector is most associated with high refresh rates and multi-monitor daisy-chaining on modern GPUs?",
     "options": ["VGA", "DVI", "DisplayPort", "Composite"], "correct": 2,
     "exp": "DisplayPort supports high bandwidth for high refresh rates/resolutions and includes Multi-Stream Transport for daisy-chaining monitors."},

    {"id": "c1-vc-1", "exam": "core1", "domain": "Virtualization & Cloud",
     "q": "What distinguishes a Type 1 hypervisor from a Type 2 hypervisor?",
     "options": ["Type 1 runs directly on hardware; Type 2 runs on top of a host OS", "Type 1 only supports Linux guests", "Type 2 is always faster", "Type 1 requires no CPU virtualization support"], "correct": 0,
     "exp": "Type 1 (bare-metal) hypervisors run directly on hardware for better performance, while Type 2 hypervisors run as an application on top of a host OS."},
    {"id": "c1-vc-2", "exam": "core1", "domain": "Virtualization & Cloud",
     "q": "Which cloud service model provides only the underlying compute, storage, and networking infrastructure?",
     "options": ["SaaS", "PaaS", "IaaS", "DaaS"], "correct": 2,
     "exp": "IaaS (Infrastructure as a Service) gives customers raw virtualized infrastructure — the customer manages the OS and above."},
    {"id": "c1-vc-3", "exam": "core1", "domain": "Virtualization & Cloud",
     "q": "What is the main benefit of a VDI (Virtual Desktop Infrastructure) setup?",
     "options": ["Faster local gaming performance", "Centrally managed desktops accessible from any device", "No need for network connectivity", "Automatic hardware upgrades"], "correct": 1,
     "exp": "VDI hosts desktop environments centrally on servers, letting users access a consistent, IT-managed desktop from thin clients or any device."},
    {"id": "c1-vc-4", "exam": "core1", "domain": "Virtualization & Cloud",
     "q": "A company uses its own private servers for sensitive data but bursts into a public cloud for extra capacity during peak load. What model is this?",
     "options": ["Public cloud", "Community cloud", "Hybrid cloud", "Private cloud"], "correct": 2,
     "exp": "Hybrid cloud combines private and public cloud resources, letting workloads move between them as needed."},
    {"id": "c1-vc-5", "exam": "core1", "domain": "Virtualization & Cloud",
     "q": "Before creating a new virtual machine on a host, what should a technician verify first?",
     "options": ["The guest OS license key only", "That the host has adequate CPU, RAM, and storage resources", "That the host is running Windows", "That no other VMs exist"], "correct": 1,
     "exp": "Host resource requirements (CPU cores, RAM, free storage) must support the new VM in addition to existing workloads, or performance will suffer."},

    {"id": "c1-ts-1", "exam": "core1", "domain": "Hardware & Network Troubleshooting",
     "q": "According to CompTIA's troubleshooting methodology, what is the first step?",
     "options": ["Implement the solution", "Establish a theory of probable cause", "Identify the problem", "Document findings"], "correct": 2,
     "exp": "The methodology starts with identifying the problem — gathering information, questioning the user, and reproducing the issue if possible."},
    {"id": "c1-ts-2", "exam": "core1", "domain": "Hardware & Network Troubleshooting",
     "q": "What does POST stand for in the context of PC startup?",
     "options": ["Power-On Self-Test", "Primary Operating System Trigger", "Peripheral Output Signal Test", "Post-Operation Status Trace"], "correct": 0,
     "exp": "POST (Power-On Self-Test) runs at boot to check core hardware before the OS loads, signaling errors via beep codes or POST codes."},
    {"id": "c1-ts-3", "exam": "core1", "domain": "Hardware & Network Troubleshooting",
     "q": "A user reports intermittent Wi-Fi drops in one part of the office. What should be checked first?",
     "options": ["Replace the router entirely", "Signal strength and interference in that area", "Reinstall the OS", "Change the DNS server"], "correct": 1,
     "exp": "Localized, intermittent Wi-Fi issues are commonly caused by weak signal or interference (distance, walls, other devices) in that specific area."},
    {"id": "c1-ts-4", "exam": "core1", "domain": "Hardware & Network Troubleshooting",
     "q": "A desktop powers on (fans spin) but shows no display output. What should be checked first?",
     "options": ["Reinstall the OS", "Cable connections and monitor power/input source", "Replace the CPU", "Update the BIOS"], "correct": 1,
     "exp": "Before assuming component failure, verify the basics: monitor is powered, correct input selected, and video cable is firmly connected."},
    {"id": "c1-ts-5", "exam": "core1", "domain": "Hardware & Network Troubleshooting",
     "q": "What does a loopback plug test?",
     "options": ["RAM integrity", "That a network port can send and receive correctly", "GPU output", "Battery health"], "correct": 1,
     "exp": "A loopback plug feeds a port's transmit signal back into its receive pins, verifying the port itself works independent of other devices."},

    {"id": "c2-os-1", "exam": "core2", "domain": "Operating Systems",
     "q": "Which Windows command-line tool displays the current IP configuration?",
     "options": ["netstat", "ipconfig", "tracert", "nslookup"], "correct": 1,
     "exp": "ipconfig displays the current network adapter configuration, including IP address, subnet mask, and default gateway."},
    {"id": "c2-os-2", "exam": "core2", "domain": "Operating Systems",
     "q": "What is the default file system for a modern Windows installation's system drive?",
     "options": ["FAT32", "exFAT", "NTFS", "ext4"], "correct": 2,
     "exp": "NTFS is the default Windows file system, supporting permissions, encryption, journaling, and large file/volume sizes."},
    {"id": "c2-os-3", "exam": "core2", "domain": "Operating Systems",
     "q": "Which Linux command lists the contents of a directory?",
     "options": ["cd", "ls", "grep", "chmod"], "correct": 1,
     "exp": "ls lists directory contents in Linux/Unix shells, analogous to 'dir' in Windows Command Prompt."},
    {"id": "c2-os-4", "exam": "core2", "domain": "Operating Systems",
     "q": "A Windows PC won't boot after a failed update. Which built-in tool is designed to diagnose and repair this?",
     "options": ["Disk Cleanup", "Startup Repair (via Windows Recovery Environment)", "Task Scheduler", "Device Manager"], "correct": 1,
     "exp": "Startup Repair, accessed through WinRE, automatically diagnoses and fixes common issues preventing Windows from booting."},
    {"id": "c2-os-5", "exam": "core2", "domain": "Operating Systems",
     "q": "Which macOS feature provides automatic, versioned backups to an external or network drive?",
     "options": ["Time Machine", "Migration Assistant", "Spotlight", "FileVault"], "correct": 0,
     "exp": "Time Machine automatically creates incremental backups, letting users restore individual files or the whole system to an earlier point."},

    {"id": "c2-sec-1", "exam": "core2", "domain": "Security",
     "q": "Which best describes a phishing attack?",
     "options": ["Overloading a server with traffic", "A fraudulent message designed to trick someone into revealing sensitive info", "Physically stealing a device", "Intercepting Wi-Fi traffic on an open network"], "correct": 1,
     "exp": "Phishing uses deceptive emails, texts, or websites impersonating a trusted source to trick users into giving up credentials or data."},
    {"id": "c2-sec-2", "exam": "core2", "domain": "Security",
     "q": "In multi-factor authentication, a smart card or hardware token represents which factor?",
     "options": ["Something you know", "Something you are", "Something you have", "Somewhere you are"], "correct": 2,
     "exp": "A physical item like a smart card or hardware token is 'something you have,' distinct from a password ('know') or biometric ('are')."},
    {"id": "c2-sec-3", "exam": "core2", "domain": "Security",
     "q": "What does two-factor authentication (2FA) add on top of a standard password login?",
     "options": ["A longer password requirement", "A second, independent verification step", "Automatic password rotation", "Encrypted storage of the password"], "correct": 1,
     "exp": "2FA requires a second, independent factor (like a code from a phone app) in addition to the password, making stolen credentials alone insufficient."},
    {"id": "c2-sec-4", "exam": "core2", "domain": "Security",
     "q": "Which type of malware encrypts a victim's files and demands payment for the decryption key?",
     "options": ["Spyware", "Ransomware", "Trojan", "Rootkit"], "correct": 1,
     "exp": "Ransomware encrypts files or locks systems, then demands payment (often cryptocurrency) in exchange for restoring access."},
    {"id": "c2-sec-5", "exam": "core2", "domain": "Security",
     "q": "What is the primary purpose of a firewall?",
     "options": ["Speed up internet connections", "Filter network traffic based on defined rules", "Back up files automatically", "Detect physical intrusions"], "correct": 1,
     "exp": "A firewall inspects and filters incoming/outgoing network traffic according to security rules, blocking unauthorized access."},

    {"id": "c2-sw-1", "exam": "core2", "domain": "Software Troubleshooting",
     "q": "An application on Windows repeatedly freezes. What is a reasonable first troubleshooting step?",
     "options": ["Reinstall Windows entirely", "Close and restart the app, and check for pending updates", "Replace the hard drive", "Disable the network adapter"], "correct": 1,
     "exp": "Start with the simplest fix: restart the app and check for updates/patches before escalating to reinstalling the OS or replacing hardware."},
    {"id": "c2-sw-2", "exam": "core2", "domain": "Software Troubleshooting",
     "q": "What does a Blue Screen of Death (BSOD) typically indicate?",
     "options": ["A minor application error", "A critical, kernel-level system error", "A full hard drive", "A weak Wi-Fi signal"], "correct": 1,
     "exp": "A BSOD is triggered by a critical error at the OS kernel or driver level that Windows cannot safely recover from, forcing a halt."},
    {"id": "c2-sw-3", "exam": "core2", "domain": "Software Troubleshooting",
     "q": "A PC has become sluggish and CPU usage is unexpectedly high with no obvious cause. What should be checked first?",
     "options": ["Monitor refresh rate", "Task Manager for unusual processes, then run an antimalware scan", "RAM voltage in BIOS", "Keyboard drivers"], "correct": 1,
     "exp": "Unexplained high CPU usage often points to a runaway process or malware; Task Manager plus an antimalware scan is the standard first check."},
    {"id": "c2-sw-4", "exam": "core2", "domain": "Software Troubleshooting",
     "q": "A user's browser keeps redirecting to unwanted search pages. This is most likely caused by which type of software?",
     "options": ["A browser hijacker/adware", "A corrupted printer driver", "A failing power supply", "A BIOS misconfiguration"], "correct": 0,
     "exp": "Unwanted redirects and injected search results are classic symptoms of a browser hijacker or adware, often bundled with other downloads."},
    {"id": "c2-sw-5", "exam": "core2", "domain": "Software Troubleshooting",
     "q": "A PC fails to boot into Windows normally right after an update. What's a good next step?",
     "options": ["Boot into Safe Mode and uninstall the recent update", "Physically replace the motherboard", "Reformat the drive immediately", "Ignore it — it will resolve itself"], "correct": 0,
     "exp": "Safe Mode loads a minimal driver set, letting you uninstall a problematic update or driver without other software interfering."},

    {"id": "c2-op-1", "exam": "core2", "domain": "Operational Procedures",
     "q": "Before making a planned change to a production system, what process should be followed?",
     "options": ["Change management process", "Immediate implementation without review", "Informal verbal approval only", "Skip documentation to save time"], "correct": 0,
     "exp": "Change management ensures planned changes are reviewed, approved, scheduled, and documented — reducing risk of unplanned outages."},
    {"id": "c2-op-2", "exam": "core2", "domain": "Operational Procedures",
     "q": "What should a technician do before opening a desktop case to work on internal components?",
     "options": ["Nothing special is needed", "Ground themselves with an ESD strap or mat", "Unplug the monitor only", "Remove the OS first"], "correct": 1,
     "exp": "Grounding with an ESD strap/mat prevents electrostatic discharge from damaging sensitive internal components."},
    {"id": "c2-op-3", "exam": "core2", "domain": "Operational Procedures",
     "q": "How should old device batteries be disposed of?",
     "options": ["Regular household trash", "Per local hazardous material regulations, typically via recycling", "Incinerated on-site", "Buried"], "correct": 1,
     "exp": "Batteries contain hazardous materials and must be disposed of or recycled according to local regulations, never in general trash."},
    {"id": "c2-op-4", "exam": "core2", "domain": "Operational Procedures",
     "q": "What does a Service Level Agreement (SLA) define?",
     "options": ["Employee vacation policy", "The expected level and terms of service between provider and customer", "Physical office layout", "Software licensing cost only"], "correct": 1,
     "exp": "An SLA formally defines expected service standards — like response times and uptime — between a provider and customer."},
    {"id": "c2-op-5", "exam": "core2", "domain": "Operational Procedures",
     "q": "Which behavior best reflects professionalism when working directly on a customer's system?",
     "options": ["Take personal calls while working", "Communicate clearly, avoid distractions, and respect the customer's property", "Skip explaining what was done", "Use jargon-heavy explanations without clarifying"], "correct": 1,
     "exp": "Professional best practice includes clear communication, avoiding distractions, and treating the customer's property and time with respect."},
]

def esc(s):
    return s.replace("'", "''")

lines = ["-- Seed data for the `questions` table. Run this AFTER schema.sql,",
         "-- in the Supabase SQL Editor.", "", "insert into questions (id, exam, domain, question, options, correct_index, explanation) values"]
row_strs = []
for q in QUESTIONS:
    options_json = json.dumps(q["options"]).replace("'", "''")
    row = f"""  ('{esc(q['id'])}', '{q['exam']}', '{esc(q['domain'])}', '{esc(q['q'])}', '{options_json}'::jsonb, {q['correct']}, '{esc(q['exp'])}')"""
    row_strs.append(row)
lines.append(",\n".join(row_strs) + "\non conflict (id) do update set\n  exam = excluded.exam,\n  domain = excluded.domain,\n  question = excluded.question,\n  options = excluded.options,\n  correct_index = excluded.correct_index,\n  explanation = excluded.explanation;\n")

with open("supabase/seed.sql", "w") as f:
    f.write("\n".join(lines))

print(f"Wrote {len(QUESTIONS)} questions to supabase/seed.sql")
